name: Node.js CI

# Trigger this workflow on every push or pull request to the 'main' branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    # Set the environment where this job will run
    runs-on: ubuntu-latest

    steps:
    # Check out the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js environment and install dependencies
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    # Run the test script
    - name: Run tests
      run: node test.js

  lint:

    # Set the environment where this job will run
    runs-on: ubuntu-latest

    steps:
    # Check out the repo code
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: Install dependencies
      run: npm install
    
    # Run the lint script
    - name: Run lint
      run: npm run lint


